cd ../../../src/
python -u enhance_dataprocess.py \
    --dataset ogbl-collab \
    --negative-sampler strict_global \
    --model gat \
    --p-model gat \
    --p-loss CE \
    --epochs 1000 \
    --runs 5 \
    --eval-steps 1 \
    --log-steps 50 \
    --eval-metric hits \
    --lr 0.0001 \
    --n-layers 2 \
    --n-hidden 512 \
    --out-hidden 512 \
    --n-heads 2 \
    --dropout 0.7 \
    --attn-drop 0.0 \
    --edge-drop 0. \
    --input-drop 0. \
    --diffusion-drop 0. \
    --weight-style HA \
    --use-valedges-as-input \
    --clip-grad-norm 1 \
    --loss-func RoL \
    --predictor MLP \
    --no-node-feat \
    --seed 0 \
    --no-pos-emb \
    --year 2010 \
    --bn \
    --q 0.4 \
    --auxiliary_size 200000 \
    --batch-size 65536 \
    --addtrain
